### ISSUE TITLE
Community usage and support

### ISSUE THREAD

**Issue by stevenscg** [BigstickCarpet/swagger-cli#11]
Hey @BigstickCarpet, I wanted to say thanks for this publishing this project.

We have been using it for years to validate and bundle dozens of yaml files into our various OpenAPI/Swagger specifications.

It still works great and we would love to see it continue to evolve and support the upcoming specification changes.

I haven't looked since last fall, but I have not found other tools that do quite the same thing.

cc @alexvolsh

**Comment by BigstickCarpet** [comment]
Hi @stevenscg.  Thanks for your kind words.  I know it's been a long time since I've done any work on this project.  Same goes for my other Swagger-related projects too.  The reason is that when I originally wrote them, I was being paid to do it as part of my day job because my employer needed them.  But I've changed jobs since then, so now any work I do on these projects is limited to my personal time.

That said, with the recent [release of Swagger 3.0](https://github.com/OAI/OpenAPI-Specification/releases/tag/3.0.0-rc0), I'm now eager to update all my Swagger projects to support the new 3.0 spec (in addition to continuing to support v2.0).  So hopefully you'll see these projects come back to life soon

**Comment by stevenscg** [comment]
Sounds great!

We are still on OAI 2.X, but will be monitoring the spec progress and updating as well. 

@ mention me for testing help or feedback if you need it.

I think I marked a few of the open issues as being potentially handy for us. I'll try to +1 those when I find them.

**Comment by BigstickCarpet** [comment]
I just released Swagger-CLI v1.0.0, which includes the latest version of Swagger-Parser.
